ktor:
    application:
        modules:
            - cat.montilivi.lallistadelacompra.ApplicationKt.module
    deployment:
        port: 8080
jwt:
    secret: "la-teva-clau-super-secreta-que-ningu-sap"
    issuer: "http://0.0.0.0:8080/"
    audience: "http://0.0.0.0:8080/"
    realm: "Accés a la llista de la compra"